language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: nosetests
env: DATABASE_URL="postgresql://postgres@localhost/ovc_test" APP_SETTINGS="config.DevelopmentConfig" PGUSER="postgres"
addons:
  postgresql: "9.3"
before_script:
  - psql -c 'create database ovc_test;'
  - psql -c 'create extension unaccent;'
  - psql -c 'CREATE TEXT SEARCH CONFIGURATION fr ( COPY = french );'